# Generated by Django 3.2 on 2021-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.CharField(blank=True, max_length=1000)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
