# Generated by Django 3.2 on 2021-04-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry',
            field=models.CharField(max_length=1000),
        ),
    ]
