# Generated by Django 3.2 on 2021-04-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_offer',
        ),
    ]
