# Generated by Django 3.2 on 2021-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210424_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='782d53e3-235c-4580-af8b-7f21547b8eb8', max_length=254),
        ),
    ]
