# Generated by Django 3.2 on 2021-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_qr_retrieval_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='d3ff8a15-ac1a-4679-b4ea-e154e1acba03', max_length=254),
        ),
    ]
