# Generated by Django 3.2 on 2021-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_qr_retrieval_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='5c30b1b1-2b67-4776-bf65-c229586fc470', max_length=254),
        ),
    ]
