# Generated by Django 3.2 on 2021-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_qr_retrieval_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='68bc164b-8246-4f6f-aa80-ec545e2cc098', max_length=254),
        ),
    ]
