# Generated by Django 3.2 on 2021-04-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_qr_retrieval_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='102bcf94-de03-4529-b393-0415a9fda8c4', max_length=254),
        ),
    ]
