# Generated by Django 3.2 on 2021-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_qr_retrieval_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='66afbba8-f2cc-49c3-8612-a5608a6ea3c0', max_length=254),
        ),
    ]
