# Generated by Django 3.2 on 2021-05-01 20:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_qr_retrieval_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital_download',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_desktop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_mobile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_desktop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_mobile',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=132, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='42bfedb6-8e31-446c-829b-a662b6183d8f', max_length=254),
        ),
    ]
