# Generated by Django 3.2 on 2021-05-01 23:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210501_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=660, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='3ce4d36c-24f1-4e13-845a-b918da64f479', max_length=254),
        ),
    ]
