# Generated by Django 3.2 on 2021-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210501_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_retrieval_key',
            field=models.CharField(default='1252fc23-5a19-4a3a-993b-0a68d51f3198', max_length=254),
        ),
    ]
